const routes = [
    {
        path:"/",
        name:"home",
        component:()=>import('@src/views/HomePage'),
        children:[
            {
                path:"main-common",
                name:"mainCommon",
                components:{
                    LeftSidebar:()=>import('@src/views/navbars/LeftNavMenuCommon'),
                    RightSidebar:{template:"<router-view></router-view>"}
                },
                children:[
                    {
                        path:"sys1",
                        name:"sys1",
                        component:()=>import('@src/views/RoleManagement')
                    },{
                        path:"sys2",
                        name:"sys2",
                        component:{template:"<h1>组织管理</h1>"}
                    },{
                        path:"",
                        name:"blank",
                        component:()=>import('@src/views/HomeBlank')
                    }
                ]
            },
            {
                path:"main-setting",
                name:"mainSetting",
                components:{
                    LeftSidebar:()=>import('@src/views/navbars/LeftNavMenuSetting'),
                    RightSidebar:{template:"<h1>欢迎访问</h1>"}
                }
            }
        ]
    },{
        path:"/login",
        name:"login",
        component:()=>import('@src/views/UsrLogin')
    },{
        path:"/regiester",
        name:"regiester",
        component:{template:'<div>regiester</div>'}
    },{
        path:'/:notMatch(.*)*',
        name:"notFound",
        component:{template:'<div>page not found</div>'}
    }
]
export default routes;
